export type ButtonVariant =
  | 'primary-xs'
  | 'primary-sm'
  | 'primary-md'
  | 'secondary-xs'
  | 'secondary-sm'
  | 'secondary-md'
  | 'tertiary-xs'
  | 'tertiary-sm'
  | 'tertiary-md'
  | 'quaternary-xxs'
  | 'quaternary-xs'
  | 'quaternary-sm'
  | 'quaternary-md'
  | 'quinary-xs'
  | 'quinary-md'
  | 'quinary-sm'

